# =============================================================================
# Heating Control Package
# =============================================================================
#
# Calendar-driven TRV control for short-term rental units.
#
# Room → Calendar mapping:
#   195.1.calendar → climate.195_1_trv
#   195.2.calendar → climate.195_2_trv
#   195.3.calendar → climate.195_3_trv + climate.195_c_trv (ensuite)
#   195.4.calendar → climate.195_4_trv
#   195.5.calendar → climate.195_5_trv
#   195.6.calendar → climate.195_6_trv
#   195.a.calendar → rooms 1+2 (unit A)
#   195.b.calendar → rooms 4+5+6 (unit B)
#   195vbr.calendar → all rooms + ensuite (whole house)
#
# Service areas (not calendar-driven):
#   195.A (Bathroom A) → 20°C default
#   195.B (Bathroom B) → 20°C default
#   195.K (Kitchen)    → 18°C default
#   195.Z (Drying Room)→ managed by fan_control package
#
# Old automations to remove:
#   - heating_enforce_limits_5x
#   - 1762440986036  (TRVs from Calendars)
#   - 1762543332903  (Set TRVs back to Heat)
#   - 1762548405049  (Manual Temp Revert)
# =============================================================================


automation:

  # ===========================================================================
  # Calendar → TRV Control
  # ===========================================================================
  # Check-in (event start + 14h = 2pm): heat to 18°C
  # Check-out (event end + 11h = 11am): drop to 14°C
  # Ignores events titled "Blocked" or "shut down"
  #
  # The room_map variable maps trigger IDs to TRV entities.
  # To add/remove rooms, edit the map and add/remove triggers.
  # ===========================================================================

  - id: heating_calendar_195
    alias: "Heating · TRVs from Calendars"
    description: "Calendar-driven heating for guest rooms"
    variables:
      room_map:
        "195_1":
          - climate.195_1_trv
        "195_2":
          - climate.195_2_trv
        "195_3":
          - climate.195_3_trv
          - climate.195_c_trv
        "195_4":
          - climate.195_4_trv
        "195_5":
          - climate.195_5_trv
        "195_6":
          - climate.195_6_trv
        "195_a":
          - climate.195_1_trv
          - climate.195_2_trv
        "195_b":
          - climate.195_4_trv
          - climate.195_5_trv
          - climate.195_6_trv
        "195vbr":
          - climate.195_1_trv
          - climate.195_2_trv
          - climate.195_3_trv
          - climate.195_4_trv
          - climate.195_5_trv
          - climate.195_6_trv
          - climate.195_c_trv
      checkin_temp: 18
      checkout_temp: 14
    triggers:
      # --- Room 1 ---
      - trigger: calendar
        entity_id: calendar.195_1_calendar
        event: start
        offset: "14:00:00"
        id: checkin_195_1
      - trigger: calendar
        entity_id: calendar.195_1_calendar
        event: end
        offset: "11:00:00"
        id: checkout_195_1

      # --- Room 2 ---
      - trigger: calendar
        entity_id: calendar.195_2_calendar
        event: start
        offset: "14:00:00"
        id: checkin_195_2
      - trigger: calendar
        entity_id: calendar.195_2_calendar
        event: end
        offset: "11:00:00"
        id: checkout_195_2

      # --- Room 3 + Ensuite ---
      - trigger: calendar
        entity_id: calendar.195_3_calendar
        event: start
        offset: "14:00:00"
        id: checkin_195_3
      - trigger: calendar
        entity_id: calendar.195_3_calendar
        event: end
        offset: "11:00:00"
        id: checkout_195_3

      # --- Room 4 ---
      - trigger: calendar
        entity_id: calendar.195_4_calendar
        event: start
        offset: "14:00:00"
        id: checkin_195_4
      - trigger: calendar
        entity_id: calendar.195_4_calendar
        event: end
        offset: "11:00:00"
        id: checkout_195_4

      # --- Room 5 ---
      - trigger: calendar
        entity_id: calendar.195_5_calendar
        event: start
        offset: "14:00:00"
        id: checkin_195_5
      - trigger: calendar
        entity_id: calendar.195_5_calendar
        event: end
        offset: "11:00:00"
        id: checkout_195_5

      # --- Room 6 ---
      - trigger: calendar
        entity_id: calendar.195_6_calendar
        event: start
        offset: "14:00:00"
        id: checkin_195_6
      - trigger: calendar
        entity_id: calendar.195_6_calendar
        event: end
        offset: "11:00:00"
        id: checkout_195_6

      # --- Unit A (rooms 1+2) ---
      - trigger: calendar
        entity_id: calendar.195_a_calendar
        event: start
        offset: "14:00:00"
        id: checkin_195_a
      - trigger: calendar
        entity_id: calendar.195_a_calendar
        event: end
        offset: "11:00:00"
        id: checkout_195_a

      # --- Unit B (rooms 4+5+6) ---
      - trigger: calendar
        entity_id: calendar.195_b_calendar
        event: start
        offset: "14:00:00"
        id: checkin_195_b
      - trigger: calendar
        entity_id: calendar.195_b_calendar
        event: end
        offset: "11:00:00"
        id: checkout_195_b

      # --- Whole house ---
      # Verify this calendar entity_id matches your new instance
      - trigger: calendar
        entity_id: calendar.195vbr_calendar
        event: start
        offset: "14:00:00"
        id: checkin_195vbr
      - trigger: calendar
        entity_id: calendar.195vbr_calendar
        event: end
        offset: "11:00:00"
        id: checkout_195vbr

    conditions:
      - condition: template
        value_template: >
          {% set s = (trigger.calendar_event.summary or '') | lower %}
          {{ 'blocked' not in s and 'shut down' not in s }}

    actions:
      - variables:
          is_checkin: "{{ trigger.id.startswith('checkin') }}"
          room_key: "{{ trigger.id | replace('checkin_', '') | replace('checkout_', '') }}"
          target_temp: "{{ checkin_temp if is_checkin else checkout_temp }}"
      - action: climate.set_hvac_mode
        target:
          entity_id: "{{ room_map[room_key] }}"
        data:
          hvac_mode: heat
      - action: climate.set_temperature
        target:
          entity_id: "{{ room_map[room_key] }}"
        data:
          temperature: "{{ target_temp | int }}"
    mode: parallel
    max: 20


  # ===========================================================================
  # Enforce Temperature Limits (14–24°C)
  # ===========================================================================
  # If a guest sets a TRV outside this range, it reverts after 1 hour.
  # Only applies to guest rooms + ensuite (not service areas).
  # ===========================================================================

  - id: heating_enforce_limits_195
    alias: "Heating · Enforce Limits"
    description: "Clamps guest room TRVs to 14-24°C range"
    variables:
      lower: 14
      upper: 24
      revert_delay: "01:00:00"
    triggers:
      - trigger: state
        entity_id:
          - climate.195_0_trv
          - climate.195_1_trv
          - climate.195_2_trv
          - climate.195_3_trv
          - climate.195_4_trv
          - climate.195_5_trv
          - climate.195_6_trv
          - climate.195_c_trv
        attribute: temperature
    actions:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ (trigger.to_state.attributes.temperature | float) > upper }}"
            sequence:
              - delay: "{{ revert_delay }}"
              - action: climate.set_temperature
                target:
                  entity_id: "{{ trigger.entity_id }}"
                data:
                  temperature: "{{ upper }}"
          - conditions:
              - condition: template
                value_template: "{{ (trigger.to_state.attributes.temperature | float) < lower }}"
            sequence:
              - delay: "{{ revert_delay }}"
              - action: climate.set_temperature
                target:
                  entity_id: "{{ trigger.entity_id }}"
                data:
                  temperature: "{{ lower }}"
    mode: restart


  # ===========================================================================
  # Force Heat Mode
  # ===========================================================================
  # TRVs sometimes flip to 'auto' or 'off' after firmware updates or
  # battery changes. This reverts them to 'heat' after 5 minutes.
  # Covers ALL TRVs including service areas.
  # ===========================================================================

  - id: heating_force_heat_195
    alias: "Heating · Force Heat Mode"
    description: "Revert any TRV that leaves heat mode"
    triggers:
      - trigger: state
        entity_id:
          - climate.195_0_trv
          - climate.195_1_trv
          - climate.195_2_trv
          - climate.195_3_trv
          - climate.195_4_trv
          - climate.195_5_trv
          - climate.195_6_trv
          - climate.195_a_trv
          - climate.195_b_trv
          - climate.195_c_trv
          - climate.195_k_trv
          - climate.195_z_trv
        to: "auto"
        for:
          minutes: 5
      - trigger: state
        entity_id:
          - climate.195_0_trv
          - climate.195_1_trv
          - climate.195_2_trv
          - climate.195_3_trv
          - climate.195_4_trv
          - climate.195_5_trv
          - climate.195_6_trv
          - climate.195_a_trv
          - climate.195_b_trv
          - climate.195_c_trv
          - climate.195_k_trv
          - climate.195_z_trv
        to: "off"
        for:
          minutes: 5
    actions:
      - action: climate.set_hvac_mode
        target:
          entity_id: "{{ trigger.entity_id }}"
        data:
          hvac_mode: heat
    mode: restart


  # ===========================================================================
  # Manual Temperature Revert (Service Areas)
  # ===========================================================================
  # If someone manually adjusts a service area TRV, revert to its default
  # after 4 hours. Prevents forgotten overrides.
  #
  # Defaults:
  #   195.A, 195.B (Bathrooms) → 20°C (mould prevention)
  #   195.K (Kitchen) → 18°C
  #   195.Z (Drying Room) → from input_number.fan_195z_trv_temperature
  # ===========================================================================

  - id: heating_manual_revert_195
    alias: "Heating · Manual Temp Revert"
    description: "Reverts service area TRVs to defaults after 4 hours"
    triggers:
      - trigger: state
        entity_id:
          - climate.195_a_trv
          - climate.195_b_trv
          - climate.195_k_trv
          - climate.195_z_trv
        attribute: temperature
        for:
          hours: 4
    actions:
      - choose:
          # Bathrooms → 20°C
          - conditions:
              - condition: template
                value_template: >
                  {{ trigger.entity_id in
                     ['climate.195_a_trv', 'climate.195_b_trv'] }}
            sequence:
              - action: climate.set_temperature
                target:
                  entity_id: "{{ trigger.entity_id }}"
                data:
                  temperature: 20

          # Kitchen → 18°C
          - conditions:
              - condition: template
                value_template: "{{ trigger.entity_id == 'climate.195_k_trv' }}"
            sequence:
              - action: climate.set_temperature
                target:
                  entity_id: "{{ trigger.entity_id }}"
                data:
                  temperature: 18

          # Drying room → from slider
          - conditions:
              - condition: template
                value_template: "{{ trigger.entity_id == 'climate.195_z_trv' }}"
            sequence:
              - action: climate.set_temperature
                target:
                  entity_id: "{{ trigger.entity_id }}"
                data:
                  temperature: "{{ states('input_number.fan_195z_trv_temperature') | int(22) }}"
    mode: restart


  # ===========================================================================
  # Master Boiler Control
  # ===========================================================================
  # Turns the boiler on when any TRV is actively heating (hvac_action =
  # "heating"), off when none are. This is demand-based — the boiler only
  # fires when at least one room needs heat.
  #
  # Old automation to remove: 1761760696188
  # ===========================================================================

  - id: heating_boiler_195
    alias: "Heating · Master Boiler Control"
    description: "Boiler on when any TRV demands heat, off when none do"
    triggers:
      - trigger: state
        entity_id:
          - climate.195_0_trv
          - climate.195_1_trv
          - climate.195_2_trv
          - climate.195_3_trv
          - climate.195_4_trv
          - climate.195_5_trv
          - climate.195_6_trv
          - climate.195_a_trv
          - climate.195_b_trv
          - climate.195_c_trv
          - climate.195_k_trv
          - climate.195_z_trv
        attribute: hvac_action
    actions:
      - variables:
          heating_trvs: >
            {% set trvs = [
              'climate.195_0_trv', 'climate.195_1_trv', 'climate.195_2_trv',
              'climate.195_3_trv', 'climate.195_4_trv', 'climate.195_5_trv',
              'climate.195_6_trv', 'climate.195_a_trv', 'climate.195_b_trv',
              'climate.195_c_trv', 'climate.195_k_trv', 'climate.195_z_trv'
            ] %}
            {{ trvs | select('is_state_attr', 'hvac_action', 'heating') | list }}
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ heating_trvs | count > 0 }}"
            sequence:
              - action: switch.turn_on
                target:
                  entity_id: switch.195_y_boiler
        default:
          - action: switch.turn_off
            target:
              entity_id: switch.195_y_boiler
    mode: single
